# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := server client

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

server: 
	@echo "==== Building server ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f server.make

client: 
	@echo "==== Building client ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f client.make

clean:
	@${MAKE} --no-print-directory -C build -f server.make clean
	@${MAKE} --no-print-directory -C build -f client.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   server"
	@echo "   client"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
